# permissions for end users to edit artifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: artifact
    app.kubernetes.io/managed-by: kustomize
  name: artifact-editor-role
rules:
- apiGroups:
  - openfluxcd.mandelsoft.org
  resources:
  - artifacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openfluxcd.mandelsoft.org
  resources:
  - artifacts/status
  verbs:
  - get
